### ISSUE TITLE
[Location Request] Plaza de Armas, Lima, Peru

### ISSUE THREAD

**Issue by ursularosien** [Nickersoft/cityhop.cafe#11]
### Do you prefer a walking or driving video (or both)?

- [x] Walking
- [ ] Driving

### Do you have any preference on the setting?

**Weather**

- [ ] Rainy
- [ ] Snowy

**Time of Day**

- [ ] Morning
- [x] Mid-day
- [ ] Evening
- [ ] Night

**Comment by Nickersoft** [comment]
[Just added!](https://www.cityhop.cafe/?v=ZTRSc1gyaDJRSWM6ZTNMMVBJWTFwTjg=). Hope you like it – also added Cusco, Peru as well.
