### ISSUE TITLE
[Location Request] Tsawwassen, BC, Canada

### ISSUE THREAD

**Issue by p13jd** [Nickersoft/cityhop.cafe#13]
### Do you prefer a walking or driving video (or both)?

- [x] Walking
- [ ] Driving

### Do you have any preference on the setting?

**Weather**

- [ ] Rainy
- [ ] Snowy

**Time of Day**

- [ ] Morning
- [ ] Mid-day
- [ ] Evening
- [ ] Night

### Do you have a YouTube video you'd recommend?

_If so, be sure it adheres to the criteria below. If you don't have a video in mind, you can delete this section._

- [ ] At least 50 minutes in length
- [ ] No narration from the person filming
- [ ] No music or soundtrack (street sounds only)
- [x] Ideally available in 4K (or at the very least 1080p)

**Link:** https://youtube.com/watch?v=

**Comment by Nickersoft** [comment]
Just added a [beautiful beach walk of Tsawwassen](https://www.cityhop.cafe/?v=a2cya2VmYnJGbjQ6U3UwMG1maTVRVVk=)! Thanks for the recommendation :)
