### ISSUE TITLE
[Location Request] Seattle, USA

### ISSUE THREAD

**Issue by coachdoug60** [Nickersoft/cityhop.cafe#15]
### Do you prefer a walking or driving video (or both)?

- [ ] Walking
- [x] Driving

### Do you have any preference on the setting?

**Weather**

- [ ] Rainy
- [ ] Snowy

**Time of Day**

- [ ] Morning
- [ ] Mid-day
- [ ] Evening
- [ ] Night

### Do you have a YouTube video you'd recommend?

_If so, be sure it adheres to the criteria below. If you don't have a video in mind, you can delete this section._

- [ ] At least 50 minutes in length
- [ ] No narration from the person filming
- [ ] No music or soundtrack (street sounds only)
- [ ] Ideally available in 4K (or at the very least 1080p)

**Link:** https://youtube.com/watch?v=

**Comment by Nickersoft** [comment]
Hey @coachdoug60, CityHop already has a driving video for Seattle, WA. Were you hoping for something else?
