### ISSUE TITLE
[Location Request] Kolkata, India

### ISSUE THREAD

**Issue by LoneWolf993** [Nickersoft/cityhop.cafe#17]
### Do you prefer a walking or driving video (or both)?

- [x] Walking
- [x] Driving

### Do you have any preference on the setting?

**Weather**

- [x] Rainy
- [ ] Snowy

**Time of Day**

- [ ] Morning
- [ ] Mid-day
- [x] Evening
- [ ] Night

**Comment by Nickersoft** [comment]
Hey @LoneWolf993, thanks for the request! I just added a [walking video](https://www.cityhop.cafe/?v=N0t6Zno4NmVzSTA6Y19fQnIxeFVWSzg=) and a [driving one](https://www.cityhop.cafe/?v=NmlHOVBwVjIwX1U6Y19fQnIxeFVWSzg=). Hope you enjoy!
