### ISSUE TITLE
Cologne, Germany

### ISSUE THREAD

**Issue by ankefc** [Nickersoft/cityhop.cafe#18]
### Do you prefer a walking or driving video (or both)?

- [x] Walking
- [ ] Driving

### Do you have any preference on the setting?

**Weather**

- [ ] Rainy
- [ ] Snowy

**Time of Day**

- [ ] Morning
- [x] Mid-day
- [ ] Evening
- [ ] Night

**Comment by Nickersoft** [comment]
[Added!](https://www.cityhop.cafe/?v=bVEySkIxcC1ESGM6Vm8tMm5vT25CY1k=)
