### ISSUE TITLE
Feature Request: Permalink for Settings

### ISSUE THREAD

**Issue by mharris1319** [Nickersoft/cityhop.cafe#19]
Would it be possible to offer the ability to permalink the city and music chosen?  Something like

`https://cityhop.cafe?city=chicago&music=lofi`

This might let us share a particular experience with another.

**Comment by Nickersoft** [comment]
Hey @mharris1319, thanks for opening an issue! So this functionality technically already _does_ exist if you click the tweet icon in the top-left (it creates a tweet containing a permalink that will open the site to the exact city + music you have selected). Though I should probably just add a "Copy Link" button, or better yet, just update the URL whenever you change the station or city.

**Comment by mharris1319** [comment]
Thank you! The existing ability is useful, thank you, although your
expressed thoughts sound even more user-friendly ...

**Comment by Nickersoft** [comment]
Just shipped a "copy link" button! Turns out during the URL update approach was too troublesome haha
