### ISSUE TITLE
[Location Request] İstanbul, Türkıye

### ISSUE THREAD

**Issue by zgordan-vv** [Nickersoft/cityhop.cafe#20]
### Do you prefer a walking or driving video (or both)?

- [x] Walking
- [ ] Driving

### Do you have any preference on the setting?

**Weather**

- [ ] Rainy
- [ ] Snowy

**Time of Day**

- [x] Morning
- [ ] Mid-day
- [ ] Evening
- [ ] Night

**Comment by Nickersoft** [comment]
[Added!](https://www.cityhop.cafe/?v=amNudTlRNURtMkE6bFAyNlVDbm9IOXM=)
