### ISSUE TITLE
[Location Request] Belgrade, Serbia

### ISSUE THREAD

**Issue by kristina-jokic** [Nickersoft/cityhop.cafe#21]
### Do you prefer a walking or driving video (or both)?

- [x] Walking
- [ ] Driving

### Do you have any preference on the setting?

**Weather**

- [ ] Rainy
- [ ] Snowy

**Time of Day**

- [ ] Morning
- [ ] Mid-day
- [ ] Evening
- [ ] Night

### Do you have a YouTube video you'd recommend?

_If so, be sure it adheres to the criteria below. If you don't have a video in mind, you can delete this section._

- [ ] At least 50 minutes in length
- [ ] No narration from the person filming
- [ ] No music or soundtrack (street sounds only)
- [ ] Ideally available in 4K (or at the very least 1080p)

**Link:** https://www.youtube.com/watch?v=NGvDS55KeCQ

**Comment by Nickersoft** [comment]
[Just added!](https://www.cityhop.cafe/?v=Tkd2RFM1NUtlQ1E6amZLZlBmeUpSZGs=)
