### ISSUE TITLE
Expand to full screen like other streaming video

### ISSUE THREAD

**Issue by wehrak** [Nickersoft/cityhop.cafe#31]
I think the title is self-explanatory. I always have cityhop open on one screen or a tablet at my desk. The ONLY thing about it I would change is the ability to get rid of the browser tab and the taskbar, like when I stream Netflix, Hulu, etc. when you expand the video to full screen.

**Comment by cristicretu** [comment]
Can be closed @Nickersoft, implementation in #33 already live @wehrak
