### ISSUE TITLE
Fullscreen Sizing Issue

### ISSUE THREAD

**Issue by MrVincetti** [Nickersoft/cityhop.cafe#39]
Firstly, my thanks to you for creating such a great site!

I've recently been running the site on my 2nd monitor while I'm working and noticed an interesting quirk after trying to use it in Fullscreen mode - It appears to be zooming into the middle of the video. Trying to troubleshoot a bit I took a side-by-side screenshot of the Kyoto Walk on the site on one screen and the YouTube video on the other with them closely synced together. I then checked the sizing of the site's image against the YouTube video and discerned that it appears to be a zoomed in window of around 640x360 in the centre of the original video. Checking the source of the site I can see the YouTube iframe appears to have a width & height definition of 640x360. Might this have something to do with it?

I did also check I wasn't completely crazy and tried the site in different browsers (Chrome first, then Edge and Firefox), and also with the 2nd monitor disabled, and got the same result each time. I tried to replicate this on another PC but it didn't have the same problem, whereas a remote desktop session I have access to... does. Quite an odd one.

Edit: I've realised that the Kyoto Walk video is 3840x2160, as is the display on the 2nd PC I tried to replicate the issue on (the others I mentioned are only 2K screens). I dropped the screen resolution down to 1920x1080 on that PC and sure enough it zooms in on the video when going fullscreen now.

**Comment by kvuzet** [comment]
this appears to be caused by the `max-aspect-ratio` media query in `src/components/UI.svelte`. removing this media query makes fullscreen work as expected.

**Comment by Nickersoft** [comment]
Hey folks! Sorry it took me so long to get around to this – the general approach taken for the videos on the site came from [here](https://codepen.io/dudleystorey/pen/PZyMrd), which is where the media queries come from. This is to ensure that the video will (almost always) take up the full dimensions of the browser. Without it, you would be much more subject to black bars around the videos.
