### ISSUE TITLE
[Location Request] Bengaluru, India

### ISSUE THREAD

**Issue by srinisandhya539** [Nickersoft/cityhop.cafe#49]
### Do you prefer a walking or driving video (or both)?
(Both would be great!)
- [x ] Walking
- [x ] Driving

### Do you have any preference on the setting?

**Weather**
Sunny, if possible
- [x ] Rainy
- [ ] Snowy

**Time of Day**

- [x ] Morning
- [x ] Mid-day
- [ ] Evening
- [ ] Night

### Do you have a YouTube video you'd recommend?

_If so, be sure it adheres to the criteria below. If you don't have a video in mind, you can delete this section._

- [ ] At least 50 minutes in length
- [ ] No narration from the person filming
- [ ] No music or soundtrack (street sounds only)
- [ ] Ideally available in 4K (or at the very least 1080p)

**Link:** https://youtube.com/watch?v=Guu6shSEbp8

**Comment by Nickersoft** [comment]
Added a [walk](https://www.cityhop.cafe/?v=MllKWUpNdFZUTGM6bFAyNlVDbm9IOXM=) and the [drive](https://www.cityhop.cafe/?v=R3V1NnNoU0VicDg6UlJiNVhWOTkzVzA=)!

**Comment by srinisandhya539** [comment]
Thank you!
