### ISSUE TITLE
[Location Request] Rio de Janeiro, Brazil

### ISSUE THREAD

**Issue by maxmetcalfe** [Nickersoft/cityhop.cafe#55]
### Do you prefer a walking or driving video (or both)?

- [x] Walking
- [ ] Driving

### Do you have any preference on the setting?

**Weather**

- [ ] Rainy
- [ ] Snowy

**Time of Day**

- [ ] Morning
- [ ] Mid-day
- [x] Evening
- [ ] Night

### Do you have a YouTube video you'd recommend?

_If so, be sure it adheres to the criteria below. If you don't have a video in mind, you can delete this section._

- [ ] At least 50 minutes in length
- [x] No narration from the person filming
- [x] No music or soundtrack (street sounds only)
- [x] Ideally available in 4K (or at the very least 1080p)

**Link:** https://www.youtube.com/watch?v=U4fLcsItJqI (only 31 minutes :()

**Comment by Nickersoft** [comment]
[Added!](https://www.cityhop.cafe/?v=VTRmTGNzSXRKcUk6bFAyNlVDbm9IOXM=)
