### ISSUE TITLE
[Location Request] Edinburgh, Scotland

### ISSUE THREAD

**Issue by augustusrivera1** [Nickersoft/cityhop.cafe#6]
### Do you prefer a walking or driving video (or both)?

- [x] Walking
- [ ] Driving

### Do you have any preference on the setting?

**Weather**

- [x] Rainy

**Time of Day**

- [x] Morning
- [x] Mid-day
- [x] Evening
- [x] Night

**Comment by Nickersoft** [comment]
Hey @augustusrivera1, thanks for requesting Edinburgh! I just added it. You can view it [here](https://www.cityhop.cafe/?v=bzlhSDR4azI1eWc6U3UwMG1maTVRVVk=). Let me know if there are any issues or anything else you'd like to see. Cheers!
