### ISSUE TITLE
[Location Request] Barcelona, Spain

### ISSUE THREAD

**Issue by stanboone** [Nickersoft/cityhop.cafe#9]
### Do you prefer a walking or driving video (or both)?

- [x] Walking
- [ ] Driving

### Do you have any preference on the setting?

**Weather**

- [ ] Rainy
- [ ] Snowy

**Time of Day**

- [x] Morning
- [x] Mid-day
- [ ] Evening
- [ ] Night

**Comment by Nickersoft** [comment]
Hey @stanboone – what is the location you are requesting? 😅

**Comment by stanboone** [comment]
Barcelona

Op wo 24 mei 2023 om 19:48 schreef Tyler Nickerson ***@***.***

**Comment by Nickersoft** [comment]
[Here ya go!](https://www.cityhop.cafe/?v=X19jaXYyRTlBNGc6U3UwMG1maTVRVVk=). I added Madrid as well :)

**Comment by stanboone** [comment]
Thanks! Can you add Los Angeles aswell?

Op wo 24 mei 2023 om 20:11 schreef Tyler Nickerson ***@***.***

**Comment by Nickersoft** [comment]
Sure! Thought I already did, but turns out I only added a driving video. Any particular part of LA? Day/night preference? Weather?

**Comment by stanboone** [comment]
A sunny day at midday or something and downtown la pls or the beach, thanks!

Op wo 24 mei 2023 om 20:26 schreef Tyler Nickerson ***@***.***

**Comment by Nickersoft** [comment]
[Just added!](https://www.cityhop.cafe/?v=VklOT1N1NXk0aWM6U3UwMG1maTVRVVk=) Also threw Venice Beach in there too :)
